### ISSUE TITLE
Pawns spamming an errored job and getting stuck

### ISSUE THREAD

**Issue by Trisscar05** [DoctorVanGogh/ExtendedStorage#17]
https://git.io/fxgoO

This is after adding Extended Storage and that addon that adds meat hooks and weapon racks to an ongoing game. Currently testing to see if taking them out fixes the issue or if something has been heavily broken.

Hoo boy, taking both out and reloading the save that had them locked in:
https://git.io/fxgKC
Also that broke the UI, most of the colonist portraits are invisible, as is the menu bar.

Updates slow due to loading times, apologies. UI destruction happens on reload of save that had ES mods installed, but if the mods are installed and an earlier save is loaded, UI is fine.

**Comment by DoctorVanGogh** [comment]
That error log contains dozens and dozens of errors from a multitude of mods, none of which at first glance are in any way related to ES.

**Comment by DoctorVanGogh** [comment]
Also... dont run B18 stuff in 1.0...

**Comment by Trisscar05** [comment]
*squints* The log was generated before 1.0 even launched, much less became downloadable. Also the errors should consist of two folders I made to hold old manual patches and dl'd mod versions, something weird going on with Mantodeans, and one error that's been around for the past couple weeks without ever specifying what it's complaining about.
Are you indicating that you see more errors not related to ES than those in the log? Cause anything else appeared once ES was enabled, so that's interesting if so.
