### ISSUE TITLE
Error when accessing multiple Apparel object stack in a Clothing Rack

### ISSUE THREAD

**Issue by Terragg** [DoctorVanGogh/ExtendedStorage#18]
Trying to right click on a stack of multiple apparel in a clothing rack output cell throws an error and prevents right-click menu/access to that stack.  Pawns still recognize items and seem interact with them normally:

![issue_error_on_multiple_stack](https://user-images.githubusercontent.com/42083065/47261237-a4373880-d498-11e8-894c-1901d16f2725.jpg)

This does not occur on a single item stack in the output cell:

![issue-no-error-on-single-item](https://user-images.githubusercontent.com/42083065/47261243-b6b17200-d498-11e8-900d-a4926e64f6e4.png)

Tested on verified Steam Install and physical wipe and reinstall of steam mod.  Known to affect Parka and Button-down shirts, no other apparel was tested.

The HugsLib dump is at: [https://git.io/fxKIM](https://git.io/fxKIM)

**Comment by DoctorVanGogh** [comment]
Thanks - fixed in c22a20436a8bf3108a04517f8bfa08fc6d9e8402
