### ISSUE TITLE
Generalize ClothingRack for weapons

### ISSUE THREAD

**Issue by DoctorVanGogh** [DoctorVanGogh/ExtendedStorage#3]
https://ludeon.com/forums/index.php?topic=34737.0

**Comment by Terragg** [comment]
I supect this issue is a place keeper, but I have this running at [Extended Sotrage Extended](https://github.com/Terragg/Extended-Storage-Extended) if you want to take a look.

**Comment by Terragg** [comment]
> The random orientation of the stacked weapons, like apparel as well.

Has been addressed with the 3.5.0.0 release.
